
cat <<EOF > alertmanager.yml
global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.ibm.com:587'
  smtp_from: 'alertmanager@ibm.com'
  smtp_auth_username: 'alertmanager@ibm.com'
  smtp_auth_password: 'yourpassword'

route:
  receiver: 'default'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'default'
    email_configs:
      - to: '83.AS-HM.24@IBM.com'
        send_resolved: true
EOF
