
apiVersion: v1
kind: Service
metadata:
  name: flask-prometheus-service
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: flask-prometheus-app
  ports:
    - port: 8080        # Service port
      targetPort: 8080  # Flask app inside container
      nodePort: 30080   # Optional: fixed NodePort (or omit for auto)
