
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-prometheus-app
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-prometheus-app
  template:
    metadata:
      labels:
        app: flask-prometheus-app
    spec:
      containers:
        - name: flask-prometheus-app
          image: mapoche/flask-prometheus-app:latest  # Replace with your Docker Hub image
          ports:
